project:
  type: website
  output-dir: docs

website:
  title: "Machine learning"
  repo-url: "https://github.com/sabarish-mn/myBlog"
  repo-actions: [source]
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

